#Mouse config ---------------------
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_BLE=y
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_PMW3610=y
# COROPIT版のカーソル方向反転はmona2_r.overlayのPMW3610ノードで指定する
# CONFIG_PMW3610_SWAP_XY=y
CONFIG_PMW3610_CPI=600
CONFIG_PMW3610_CPI_DIVIDOR=1
CONFIG_PMW3610_SCROLL_TICK=16
CONFIG_PMW3610_INVERT_SCROLL_X=y
# CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
# CONFIG_PMW3610_LOG_LEVEL_DBG=y
# CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=300 // <--see Troubleshooting

#Encoder config -------------------
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#Battery config -------------------
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

#Layer LED config -------------------
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y

#ZMK Studio config -------------------
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

#Bluetooth config -------------------
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
